FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir Django==5.2.11 django-cors-headers==4.9.0 openpyxl==3.1.5

EXPOSE 9001

CMD ["python", "frontend/manage.py", "runserver", "0.0.0.0:9001"]
