FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
WORKDIR /app
RUN pip install --no-cache-dir \
    transformers==4.57.1 accelerate peft \
    fastapi uvicorn pydantic numpy python-dotenv \
    google-cloud-texttospeech \
    tensorflow librosa joblib scikit-learn soundfile
COPY care_ai/ /app/care_ai/
EXPOSE 8300
CMD ["python", "-m", "care_ai.server"]
